_FLOAT_VARS = []
_INT_VARS = []

DATABASE_URL = ""
SNCF_API_KEY = ""
BASE_URL = "https://api.sncf.com/v1"
LOG_LEVEL = "INFO"
DATAGOUVFR_DATASET_ID = "641b456a5374b1bdc9dce4cf"
DATAGOUVFR_API_KEY = ""
