version: '3'

services:
  db:
    image: postgres:14.5
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tr_rm
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
